---
- hosts: all
  become: true
  become_user: root
  vars:
    create_containers: 1
    default_container_name: docker
    default_container_image: zuzanay/ubuntutest_version1

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Copy Docker Image 
      copy:
        src: /home/ansible/homework/e1/zuzanay_ubuntutest_version1.tar.gz
        dest: /home/ansible/homework/e1
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/ansible/homework/e1/zuzanay_ubuntutest_version1.tar.gz
        dest: /home/ansible/homework/e1
        remote_src: yes

    - name: load the docker image
      command: docker load --input /home/ansible/homework/e1/zuzanay_ubuntutest_version1.tar
 
    - name: start docker service
      service: 
        name: docker
        state: started
        enabled: yes
      become: true
      
